services:
  app:
    build:
      context: ..
      dockerfile: .production/Dockerfile
    container_name: portofolio-app
    restart: unless-stopped
    env_file: .env 
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portofolio.rule=Host(`zoelfikars.site`) || Host(`api.zoelfikars.site`)"
      - "traefik.http.routers.portofolio.entrypoints=web"
      - "traefik.http.services.portofolio.loadbalancer.server.port=80"

networks:
  traefik_net:
    external: true