services:
  app:
    image: ghcr.io/zoelfikars/laravue-portofolio:latest
    container_name: portofolio-app
    restart: unless-stopped
    env_file: .env 
    networks:
      - traefik_net
  web:
    image: nginx:alpine
    container_name: portofolio-web
    restart: unless-stopped
    volumes:
      - app_data:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portofolio-front.rule=Host(`zoelfikars.site`)"
      - "traefik.http.routers.portofolio-front.entrypoints=web"
      - "traefik.http.services.portofolio-front.loadbalancer.server.port=80"
      - "traefik.http.routers.portofolio-api.rule=Host(`api.zoelfikars.site`)"
      - "traefik.http.routers.portofolio-api.entrypoints=web"
      - "traefik.http.services.portofolio-api.loadbalancer.server.port=81"

volumes:
  app_data: 

networks:
  traefik_net:
    external: true