name: Deploy to Home Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Deploy Docker
        run: |
          # Copy .env ke folder .production supaya terbaca oleh docker compose
          cp ~/app/laravue-portofolio/.env ./.production/.env
          
          # Pindah ke folder production
          cd .production
          
          # Bersihkan total dan build
          docker compose down --volumes --remove-orphans
          docker compose up -d --build
          
          # Tunggu agar PHP-FPM siap
          sleep 5
          
          # Eksekusi migrasi (nama service harus sesuai di .production/docker-compose.yml)
          docker compose exec -T app php artisan migrate --force