name: Deploy to Home Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Deploy Docker
        run: |
          # 1. Pastikan folder .production ada
          cd .production
          
          # 2. Ambil .env
          cp ~/app/laravue-portofolio/.env .env
          
          # 3. Turunkan container lama (jika ada)
          docker compose down --remove-orphans
          
          # 4. Build dan Up
          docker compose up -d --build
          
          # 5. Beri jeda dan migrate
          sleep 5
          docker compose exec -T app php artisan migrate --force