name: Deploy to Home Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Deploy Docker
        run: |
          # Pindah ke direktori tempat docker-compose kamu berada (opsional)
          # cd ~/app/laravue-portofolio 
          
          # Build image secara lokal (lebih cepat, tanpa internet)
          docker build -t laravue-app:latest -f ./.production/Dockerfile .
          
          # Restart container
          docker compose up -d
          
          # Jalankan artisan commands
          docker compose exec -T app php artisan migrate --force
          
          # Bersihkan image lama yang tidak terpakai
          docker image prune -f