name: Deploy to Home Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Deploy Docker
        run: |
          # 1. Copy .env ke folder root (karena kita akan jalan dari root)
          cp ~/app/laravue-portofolio/.env .env
          
          # 2. Jalankan docker compose dengan menunjuk file di folder .production
          # Gunakan flag -f untuk menunjuk lokasi file compose-nya
          docker compose -f .production/docker-compose.yml down --remove-orphans
          docker compose -f .production/docker-compose.yml up -d --build
          
          # 3. Beri jeda agar container stabil
          sleep 5
          
          # 4. Eksekusi migrasi
          # Nama container biasanya otomatis jadi: production-app-1 atau sesuai container_name
          docker compose -f .production/docker-compose.yml exec -T app php artisan migrate --force
          
          # 5. Bersihkan image lama
          docker image prune -f