name: Deploy to Production

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  # JOB 1: BUILD (Tidak butuh VPN, karena dia kerja di Cloud GitHub)
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.production/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

  # JOB 2: DEPLOY (Ini yang butuh VPN buat masuk ke Server kamu)
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      # 1. NYALAKAN VPN DI SINI
      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: latest

      # 2. SSH LEWAT VPN
      - name: Deploy to Server via SSH
        # KITA GANTI KE VERSI TERBARU (master) BIAR LEBIH PINTAR
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: 22
          timeout: 60s
          command_timeout: 30m
          # Parameter ini baru bisa jalan di versi master
          command_args: "-o StrictHostKeyChecking=no"
          debug: true # Kita nyalakan debug biar ketahuan salahnya dimana          
          script: |
            # Login ke GHCR
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Masuk folder
            mkdir -p ~/app/laravue-portofolio
            cd ~/app/laravue-portofolio

            # Pull & Restart
            docker compose pull
            docker compose up -d
            
            # Migrate & Clean
            docker compose exec -T app php artisan migrate --force
            docker image prune -f